apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-with-git
    appGroup: eKartApp
    purpose: precious
  name: app-with-git
  namespace: voyager-ns
spec:
  ports:
    - port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app: app-with-git
  type: ClusterIP
status:
  loadBalancer: {}